# Generated by Django 4.1.5 on 2023-01-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastn', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=60)),
                ('date', models.DateField(verbose_name=2023)),
            ],
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
