# Generated by Django 4.1.5 on 2023-01-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almeja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
